const config = (module.exports = {});
config.port = 9050;
config.host = '127.0.0.1';
config.player = '--vlc';
config.remove = true;
config.blocklist = 'auto';
config.path = 'tmp';
config.printmag = false;
config.health = true;
config.subtitles = 'none';
